---
- name: "Download Filebeat's rpm"
  get_url:
    url: "http://46.0.192.144/elasticsearch/filebeat-{{ filebeat_version }}-x86_64.rpm"
    dest: "files/filebeat-{{ filebeat_version }}-x86_64.rpm"
    validate_certs: false
  register: download_filebeat
  delegate_to: localhost
  until: download_filebeat is succeeded
  when: filebeat_install_type == 'remote'
- name: Copy Filebeat to managed node
  copy:
    src: "files/filebeat-{{ filebeat_version }}-x86_64.rpm"
    mode: 0755
    dest: "/tmp/filebeat-{{ filebeat_version }}-x86_64.rpm"
